Move to Jakarta based application servers
xwiki/xwiki-commons pull request #1075
Opened 2024-09-02 08:24 UTC by tmortagne

# Jira URL

* https://jira.xwiki.org/browse/XCOMMONS-2962
* https://jira.xwiki.org/browse/XCOMMONS-2963
* https://jira.xwiki.org/browse/XCOMMONS-2777
* https://jira.xwiki.org/browse/XCOMMONS-2994
* https://jira.xwiki.org/browse/XCOMMONS-2797

# Changes

## Description

The idea is to do just enough for XWiki to work in jakarta based Application servers (Jetty 11+, Tomcat 10+).

### Jakarta WebSocket 2.1.1

XWiki has been migrated to WebSocket 2.1.1 without any kind of bridge so every WebSocket related APIs are broken.

### Jakarta Servlet 5.0

* A javax.servlet <-> jakarta.servlet has been introduced.
* No servlet related API should be broken except the Filters and referenced in web.xml which have been migrated without keeping a `javax.servlet` version.

### Jakarta Inject 2.0.1

It was probably not strictly required, but both javax and jakarta inject APIs are now supported at the same time.

#### TODO

* Migrate Bean Validation to Jakarta: I'm afraid it won't be possible to support both javax and jakarta flavors of Bean Validation. Fortunately it's not actually used much in practice and since the use of Bean Validation in XWiki is only about putting annotations in macro/filter properties it's possible to have both in the same class (the class does not need the annotation to exist in the classloader to be loaded).

### Not migrated

It's not strictly required to migrate everything to jakarta.* to work in a jakarta application server (we should do it eventually of course, but we can to that in several steps):

See https://design.xwiki.org/xwiki/bin/view/Proposal/Jakartamigration for more details.

# Executed Tests

# Expected merging strategy

* Prefers squash: Yes

2025-01-08 08:47 UTC, manuelleduc commented
> I also tried to migrate as little as possible from javax to jakarta as a way to test the bridges.

@tmortagne it this a temporary step to validate the bridge? i.e., do we want to move all `javax` to `jakarta` quickly?

2025-01-08 09:13 UTC, tmortagne commented
> @tmortagne it this a temporary step to validate the bridge? i.e., do we want to move all javax to jakarta quickly?

The way I see it, the idea would be to migrate existing code only after a few releases, and we are happy with how things are behaving. But new code should obviously try to use jakarta APIs as much as possible (I tried to provide jakarta versions of all the APIs and to deprecate javax based one, at least for stuff which have been migrated already like servlet and inject).

2025-01-08 10:55 UTC, michitux requested changes
There seem to be subtle bugs in some of the adapters and converters. It would be great if we could have automated tests that protect against such bugs similar to the tests that I wrote for listeners, see, e.g., https://github.com/xwiki/xwiki-rendering/blob/9ac37383fe66215642ffc9f01e456c294a9f422f/xwiki-rendering-api/src/test/java/org/xwiki/rendering/listener/chaining/AbstractChainingListenerTest.java#L191. There also appear to be quite some TODOs left, do you plan to implement the missing parts or at least document clearly what is unsupported?

2025-01-08 10:55 UTC, michitux commented on xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/src/main/java/org/xwiki/component/annotation/ComponentDescriptorFactory.java
>  import javax.annotation.Priority;
There is no replacement for `Priority`? Or you just decided not to migrate that yet?

2025-01-08 10:55 UTC, michitux commented on xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/src/main/java/org/xwiki/component/annotation/DefaultComponentDependencyFactory.java
> +            dependency = null;
This else doesn't seem necessary as the variable is already initialized with `null`. Also, isn't this a behavior change?

2025-01-08 10:55 UTC, michitux commented on xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/src/test/java/org/xwiki/component/JavaxProviderIntegrationTest.java
> +
According to https://dev.xwiki.org/xwiki/bin/view/Community/CodeStyle/JavaCodeStyle/#HImports, static imports should be last, not first, so the change here seems wrong.

2025-01-08 10:55 UTC, michitux commented on xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-servlet/src/main/java/org/xwiki/environment/internal/ServletEnvironment.java
> +import jakarta.servlet.ServletContext;
I wonder if we should add a special rule for `jakarta` imports, e.g., to put them after `javax`?

2025-01-08 10:55 UTC, michitux commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-common/pom.xml
> +    <xwiki.jacoco.instructionRatio>0.0</xwiki.jacoco.instructionRatio>
No tests?

2025-01-08 10:55 UTC, michitux commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-common/src/main/java/org/xwiki/jakartabridge/internal/JavaxToJakartaCollection.java
> +        if (a.length == 0) {
This looks wrong to me. According to my understanding, a new array should be allocated when the passed array is too small. Also, doesn't this mean that `toArray()` always returns an empty array?

2025-01-08 10:55 UTC, michitux commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-common/src/main/java/org/xwiki/jakartabridge/internal/JavaxToJakartaCollection.java
> +            .remove(JakartaBridge.toJakarta((Collection<X>) c, this.javaxProvider, this.jakartaProvider));
Calling `remove` in `containsAll` seems surprising.

2025-01-08 10:55 UTC, michitux commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-servlet/src/main/java/org/xwiki/jakartabridge/servlet/JakartaServletBridge.java
> +        return Collections.enumeration(Collections.list(jakarta).stream().map(JakartaServletBridge::toJavax).toList());
Converting first to a list seems quite a waste, according to [this answer](https://stackoverflow.com/a/33245847) it should also be possible to directly create a stream based on an iterator. Otherwise, I'm wondering if it wouldn't be cleaner to use a regular for-loop to directly create a list with the correct elements.

2025-01-08 10:55 UTC, michitux commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-servlet/src/main/java/org/xwiki/jakartabridge/servlet/JakartaServletBridge.java
> +        return EnumSet.copyOf(jakarta.stream().map(JakartaServletBridge::toJavax).collect(Collectors.toList()));
Why don't you directly collect the result of the stream in an `EnumSet`?

```suggestion
        return jakarta.stream().map(JakartaServletBridge::toJavax).collect(Collectors.toCollection(() -> EnumSet.noneOf(javax.servlet.DispatcherType.class)));
```

2025-01-08 10:55 UTC, michitux commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-servlet/src/main/java/org/xwiki/jakartabridge/servlet/JakartaServletBridge.java
> +        return EnumSet.copyOf(javax.stream().map(JakartaServletBridge::toJakarta).collect(Collectors.toList()));
Same here as above.

2025-01-08 10:55 UTC, michitux commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-servlet/src/main/java/org/xwiki/jakartabridge/servlet/JakartaServletBridge.java
> +        // TODO
You still plan to implement these methods?

2025-01-08 10:55 UTC, michitux commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-servlet/src/main/java/org/xwiki/jakartabridge/servlet/internal/JakartaToJavaxAsyncContext.java
> +        // TODO
Do you still plan to implement this?

2025-01-08 10:55 UTC, michitux commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-servlet/src/main/java/org/xwiki/jakartabridge/servlet/internal/JakartaToJavaxHttpServletRequest.java
> +        // TODO
You still plan to implement this?

2025-01-08 11:00 UTC, michitux commented on xwiki-commons-core/xwiki-commons-websocket/pom.xml
> +      <groupId>org.xwiki.commons</groupId>
How is this change related to the move to jakarta?

2025-01-08 11:11 UTC, michitux commented on xwiki-commons-core/xwiki-commons-legacy/xwiki-commons-legacy-component/xwiki-commons-legacy-component-default/src/main/java/org/xwiki/component/embed/GenericProvider.java
> + * @deprecated
Isn't this missing a comment which class should be used instead?

2025-01-08 11:11 UTC, michitux commented on xwiki-commons-core/xwiki-commons-websocket/pom.xml
> +      <groupId>org.xwiki.commons</groupId>
How is this change related to the move to jakarta?

2025-01-08 11:25 UTC, tmortagne commented on xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/src/main/java/org/xwiki/component/annotation/ComponentDescriptorFactory.java
>  import javax.annotation.Priority;
I did not really migrate `javax.annotation` yet. It was not really necessary for jakarta application servers.

2025-01-08 11:31 UTC, tmortagne commented on xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/src/main/java/org/xwiki/component/annotation/ComponentAnnotationLoader.java
> +                // Handle javax.inject.Provider (retro-compatibility since **feature-deploy-jakarta**)
There are plenty of since to resolve, I need to be sure in which merge it's going to be merged first...

2025-01-08 11:35 UTC, tmortagne commented on xwiki-commons-core/xwiki-commons-component/xwiki-commons-component-default/src/test/java/org/xwiki/component/JavaxProviderIntegrationTest.java
> +
Indeed, not sure how it ended there.

2025-01-08 13:16 UTC, tmortagne commented on xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-servlet/src/main/java/org/xwiki/environment/internal/ServletEnvironment.java
> +import jakarta.servlet.ServletContext;
It would indeed probably make sense. It's easy to configure in Eclipse, not sure how it works for IDEA.

2025-01-08 13:18 UTC, tmortagne commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-common/src/main/java/org/xwiki/jakartabridge/internal/JavaxToJakartaCollection.java
> +        if (a.length == 0) {
This code is indeed wrong. Fixing.

2025-01-08 13:28 UTC, tmortagne commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-servlet/src/main/java/org/xwiki/jakartabridge/servlet/JakartaServletBridge.java
> +        return Collections.enumeration(Collections.list(jakarta).stream().map(JakartaServletBridge::toJavax).toList());
I was lazy, but what would actually make the most sense in terms of performance is creating an Enumeration wrapper which manipulate the other one in its implementation, like I did for the other collections in `org.xwiki.jakartabridge.internal`. I'm going to add one more helper for Enumeration.

2025-01-08 13:50 UTC, tmortagne commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-servlet/src/main/java/org/xwiki/jakartabridge/servlet/JakartaServletBridge.java
> +        // TODO
Not immediately, it did not seem to worth the trouble given that we have not using those concepts in XWiki. But eventually, probably.

2025-01-08 13:53 UTC, tmortagne commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-servlet/src/main/java/org/xwiki/jakartabridge/servlet/JakartaServletBridge.java
> +        return EnumSet.copyOf(jakarta.stream().map(JakartaServletBridge::toJavax).collect(Collectors.toList()));
I just did not notice this way to use collect yet.

2025-01-08 14:00 UTC, tmortagne commented on xwiki-commons-core/xwiki-commons-legacy/xwiki-commons-legacy-component/xwiki-commons-legacy-component-default/src/main/java/org/xwiki/component/embed/GenericProvider.java
> + * @deprecated
This should have never been public in the first place, there are only internal alternatives. I forgot about that one in the pull request description, indeed.

2025-01-08 14:04 UTC, tmortagne commented on xwiki-commons-core/xwiki-commons-websocket/pom.xml
> +      <groupId>org.xwiki.commons</groupId>
I doubt it is needed. I guess I just modified those by reflex for consistency.

2025-01-08 14:05 UTC, michitux commented on xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-servlet/src/main/java/org/xwiki/environment/internal/ServletEnvironment.java
> +import jakarta.servlet.ServletContext;
Easy to configure in IDEA, too, I think we provide the configuration with the configuration we provide for IDEA.

2025-01-08 14:17 UTC, tmortagne commented on xwiki-commons-core/xwiki-commons-environment/xwiki-commons-environment-servlet/src/main/java/org/xwiki/environment/internal/ServletEnvironment.java
> +import jakarta.servlet.ServletContext;
Sent https://forum.xwiki.org/t/add-a-special-ordering-location-for-jakarta-imports/16228.

2025-01-10 10:54 UTC, michitux commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-servlet/src/main/java/org/xwiki/jakartabridge/servlet/JakartaServletBridge.java
> +        // TODO
It just seems strange to me that some random methods are missing without any indication in any documentation. I find this dangerous as it could cause random failures at runtime. You're certain that those methods that are missing won't be needed by some code that we don't control? I haven't fully checked where exactly those wrappers are used. In any case, if there is any risk, we should make sure that we don't use these wrappers in XS itself.

2025-01-10 10:58 UTC, tmortagne commented on xwiki-commons-core/xwiki-commons-jakartabridge/xwiki-commons-jakartabridge-servlet/src/main/java/org/xwiki/jakartabridge/servlet/JakartaServletBridge.java
> +        // TODO
> In any case, if there is any risk, we should make sure that we don't use these wrappers in XS itself.

Unless I don't understand what you mean here, I already answered that: "we are not using those concepts in XWiki". Each of those methods is a rabbit hole of new wrappers to add.

2025-01-10 11:08 UTC, michitux commented on xwiki-commons-core/xwiki-commons-legacy/xwiki-commons-legacy-component/xwiki-commons-legacy-component-default/src/main/java/org/xwiki/component/embed/GenericProvider.java
> + * @deprecated
I would have just expected at least some comment here for potential (even if unlikely) users of that class what they should do. However, I just checked, and it's probably not used anymore after your change so it seems okay.

2025-01-10 11:08 UTC, michitux approved these changes

2025-01-10 12:58 UTC, merged